### ISSUE TITLE
DCI_CASCADE property in .tcl file contradicts schematic

### ISSUE THREAD

**Issue by hansfbaier** [enclustra/Mercury_KX2_ST1_Reference_Design#2]
Hello,
I found a contradiction between the .tcl settings and schematic.
In the .tcl file, we read:
```tcl
set_property DCI_CASCADE {32} [get_iobanks 34]
```
But in the schematic, the DDR3_VRP/DDR3_VRN reference resistors are connected to the reference
inputs of Bank 34, while the reference inputs of bank 32 and 33 are conected to the onboard LEDs:
![image](https://user-images.githubusercontent.com/148607/169247981-2261bb71-7647-4599-ac4d-65f8de104764.png)

Which means that, according to the schematic and UG471, the configuration should be as follows:
```tcl
set_property DCI_CASCADE {34} [get_iobanks 32 33]
```
Because 34 is the master bank with the reference resistors connected and 32 and 33 are the slave banks.
(see also https://support.xilinx.com/s/article/47499?language=en_US)

**Comment by dduerner** [comment]
Hi Hans

I think you are correct for UCF syntax, but for XDC syntax it is seems to be correct in the reference design, as written in the [UG912 on page 192/193](https://docs.xilinx.com/api/khub/documents/jISrzboRt9OLnI_EyEtnZw/content?Ft-Calling-App=ft%2Fturnkey-portal&Ft-Calling-App-Version=3.11.27&filename=ug912-vivado-properties.pdf#page=192&zoom=150,-120,78):

```
set_property DCI_CASCADE {slave_banks} [get_iobanks master_bank]
```

In [UG471 on page 46/47](https://docs.xilinx.com/api/khub/documents/IbGcnPFe6eF19RHma_Y~IA/content?Ft-Calling-App=ft%2Fturnkey-portal&Ft-Calling-App-Version=3.11.27&filename=ug471_7Series_SelectIO.pdf#page=46&zoom=auto,-205,131) the UCF syntax is mentioned. 

Further [Xilinx Article 38913](https://support.xilinx.com/s/article/38913?language=en_US) shows the difference between the XDC & UCF syntax.

**Comment by hansfbaier** [comment]
Yes that's the way it really seems to work. Thanks!
